#pragma once

#include <vulkan/vulkan_core.h>

namespace ltracer
{
namespace procedures
{

// Device Pointer Functions
extern PFN_vkCmdTraceRaysKHR pvkCmdTraceRaysKHR;
extern PFN_vkGetBufferDeviceAddressKHR pvkGetBufferDeviceAddressKHR;
extern PFN_vkCreateRayTracingPipelinesKHR pvkCreateRayTracingPipelinesKHR;
extern PFN_vkGetAccelerationStructureBuildSizesKHR pvkGetAccelerationStructureBuildSizesKHR;
extern PFN_vkCreateAccelerationStructureKHR pvkCreateAccelerationStructureKHR;
extern PFN_vkGetAccelerationStructureDeviceAddressKHR pvkGetAccelerationStructureDeviceAddressKHR;
extern PFN_vkCmdBuildAccelerationStructuresKHR pvkCmdBuildAccelerationStructuresKHR;
extern PFN_vkDestroyAccelerationStructureKHR pvkDestroyAccelerationStructureKHR;
extern PFN_vkGetRayTracingShaderGroupHandlesKHR pvkGetRayTracingShaderGroupHandlesKHR;

void grabDeviceProcAddr(VkDevice logicalDevice);

} // namespace procedures
} // namespace ltracer
